In [63]:
import tensorflow as tf

In [64]:
import os

In [65]:
os.getcwd() #get current working directory

'C:\\Users\\yash\\Documents\\OpenCvclass\\project\\Tumorclassification'

In [66]:
# !pip install unrar


In [67]:
import unrar

In [68]:
# rar_file_path = '/content/Tumorclassification.rar'

In [69]:
# Specify the directory where you want to extract the contents
# extract_dir = '/content'

In [70]:
# !pip install rarfile

# import rarfile
# # Now, let's extract the contents
# with rarfile.RarFile(rar_file_path, 'r') as rf:
#     rf.extractall(extract_dir)

# print(f"Extracted to: {extract_dir}")

In [71]:
categories=['small_Benign','small_Malignant']
#create list of category

In [72]:
# data = []

# for category in categories:
#     path = os.path.join('train', category)
#     print(path)

#     label = categories.index(category)
#     print(label)

In [73]:
import os
import cv2

# Define the categories
categories=['small_Benign','small_Malignant']

data = []

# Loop through each category
for category in categories:
    path = os.path.join('train', category)  # Assuming the folders are in the root of your Google Drive
    label = categories.index(category)

    # Loop through each file in the category folder
    for file in os.listdir(path):
        img_path = os.path.join(path, file)

        # Read the image
        img = cv2.imread(img_path)

        # Resize the image to 224x224
        try:
            img = cv2.resize(img, (224, 224))
        except Exception as e:
            print(f"Error processing {img_path}: {str(e)}")
            continue

        # Append the image and its label to the data list
        data.append([img, label])

# Now you have a list 'data' containing image-label pairs
# Each element of 'data' is a list [image, label], where 'image' is a numpy array and 'label' is an integer
# You can further process this data for your machine learning model


In [74]:
#how many images inthe dataset
len(data)

200

In [75]:
import random
random.shuffle(data)

In [76]:
data

[[array([[[160, 140, 205],
          [158, 141, 205],
          [160, 143, 207],
          ...,
          [169, 151, 204],
          [165, 147, 200],
          [160, 142, 195]],
  
         [[157, 137, 202],
          [155, 138, 202],
          [156, 140, 204],
          ...,
          [172, 154, 207],
          [168, 150, 203],
          [163, 145, 198]],
  
         [[153, 136, 200],
          [153, 136, 200],
          [153, 137, 201],
          ...,
          [174, 156, 209],
          [170, 152, 205],
          [165, 147, 200]],
  
         ...,
  
         [[161, 140, 203],
          [166, 145, 208],
          [171, 150, 212],
          ...,
          [179, 163, 216],
          [184, 168, 221],
          [186, 170, 223]],
  
         [[161, 140, 203],
          [164, 143, 206],
          [167, 146, 208],
          ...,
          [181, 165, 218],
          [185, 169, 222],
          [186, 170, 223]],
  
         [[163, 142, 205],
          [161, 140, 203],
          [161, 140, 202

In [77]:
#split the input
X=[]
Y=[]
for feature,label in data:
    X.append(feature)
    Y.append(label)

In [78]:
from collections import Counter

label_counts = Counter(Y)
print(label_counts)

Counter({1: 100, 0: 100})


In [79]:
X

[array([[[160, 140, 205],
         [158, 141, 205],
         [160, 143, 207],
         ...,
         [169, 151, 204],
         [165, 147, 200],
         [160, 142, 195]],
 
        [[157, 137, 202],
         [155, 138, 202],
         [156, 140, 204],
         ...,
         [172, 154, 207],
         [168, 150, 203],
         [163, 145, 198]],
 
        [[153, 136, 200],
         [153, 136, 200],
         [153, 137, 201],
         ...,
         [174, 156, 209],
         [170, 152, 205],
         [165, 147, 200]],
 
        ...,
 
        [[161, 140, 203],
         [166, 145, 208],
         [171, 150, 212],
         ...,
         [179, 163, 216],
         [184, 168, 221],
         [186, 170, 223]],
 
        [[161, 140, 203],
         [164, 143, 206],
         [167, 146, 208],
         ...,
         [181, 165, 218],
         [185, 169, 222],
         [186, 170, 223]],
 
        [[163, 142, 205],
         [161, 140, 203],
         [161, 140, 202],
         ...,
         [183, 167, 220],
  

In [80]:
Y

[1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0]

In [81]:
len(X),len(Y)

(200, 200)

In [82]:
import numpy as np
#convert numpy array (x 2d and y 1d)
X=np.array(X)
Y=np.array(Y)

In [83]:
X

array([[[[160, 140, 205],
         [158, 141, 205],
         [160, 143, 207],
         ...,
         [169, 151, 204],
         [165, 147, 200],
         [160, 142, 195]],

        [[157, 137, 202],
         [155, 138, 202],
         [156, 140, 204],
         ...,
         [172, 154, 207],
         [168, 150, 203],
         [163, 145, 198]],

        [[153, 136, 200],
         [153, 136, 200],
         [153, 137, 201],
         ...,
         [174, 156, 209],
         [170, 152, 205],
         [165, 147, 200]],

        ...,

        [[161, 140, 203],
         [166, 145, 208],
         [171, 150, 212],
         ...,
         [179, 163, 216],
         [184, 168, 221],
         [186, 170, 223]],

        [[161, 140, 203],
         [164, 143, 206],
         [167, 146, 208],
         ...,
         [181, 165, 218],
         [185, 169, 222],
         [186, 170, 223]],

        [[163, 142, 205],
         [161, 140, 203],
         [161, 140, 202],
         ...,
         [183, 167, 220],
        

In [84]:
Y

array([1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 0])

In [85]:
X.shape

(200, 224, 224, 3)

In [86]:
Y.shape

(200,)

In [87]:
X.ndim

4

In [88]:
#scaler :min max scaler
#RGB (0-255,0-255,0-255)
X=X/255

In [89]:
X

array([[[[0.62745098, 0.54901961, 0.80392157],
         [0.61960784, 0.55294118, 0.80392157],
         [0.62745098, 0.56078431, 0.81176471],
         ...,
         [0.6627451 , 0.59215686, 0.8       ],
         [0.64705882, 0.57647059, 0.78431373],
         [0.62745098, 0.55686275, 0.76470588]],

        [[0.61568627, 0.5372549 , 0.79215686],
         [0.60784314, 0.54117647, 0.79215686],
         [0.61176471, 0.54901961, 0.8       ],
         ...,
         [0.6745098 , 0.60392157, 0.81176471],
         [0.65882353, 0.58823529, 0.79607843],
         [0.63921569, 0.56862745, 0.77647059]],

        [[0.6       , 0.53333333, 0.78431373],
         [0.6       , 0.53333333, 0.78431373],
         [0.6       , 0.5372549 , 0.78823529],
         ...,
         [0.68235294, 0.61176471, 0.81960784],
         [0.66666667, 0.59607843, 0.80392157],
         [0.64705882, 0.57647059, 0.78431373]],

        ...,

        [[0.63137255, 0.54901961, 0.79607843],
         [0.65098039, 0.56862745, 0.81568627]

In [90]:
#split the input
X=[]
Y=[]
for feature,label in data:
    X.append(feature)
    Y.append(label)

In [91]:
X

[array([[[160, 140, 205],
         [158, 141, 205],
         [160, 143, 207],
         ...,
         [169, 151, 204],
         [165, 147, 200],
         [160, 142, 195]],
 
        [[157, 137, 202],
         [155, 138, 202],
         [156, 140, 204],
         ...,
         [172, 154, 207],
         [168, 150, 203],
         [163, 145, 198]],
 
        [[153, 136, 200],
         [153, 136, 200],
         [153, 137, 201],
         ...,
         [174, 156, 209],
         [170, 152, 205],
         [165, 147, 200]],
 
        ...,
 
        [[161, 140, 203],
         [166, 145, 208],
         [171, 150, 212],
         ...,
         [179, 163, 216],
         [184, 168, 221],
         [186, 170, 223]],
 
        [[161, 140, 203],
         [164, 143, 206],
         [167, 146, 208],
         ...,
         [181, 165, 218],
         [185, 169, 222],
         [186, 170, 223]],
 
        [[163, 142, 205],
         [161, 140, 203],
         [161, 140, 202],
         ...,
         [183, 167, 220],
  

In [55]:
from collections import Counter

label_counts = Counter(Y)
print(label_counts)

Counter({1: 100, 0: 100})


In [56]:
X

[array([[[114, 105, 155],
         [120, 111, 161],
         [129, 118, 168],
         ...,
         [ 75,  74, 116],
         [ 72,  71, 113],
         [ 71,  70, 112]],
 
        [[116, 107, 157],
         [120, 111, 161],
         [127, 116, 166],
         ...,
         [ 76,  75, 117],
         [ 72,  71, 113],
         [ 69,  68, 110]],
 
        [[120, 111, 161],
         [120, 111, 161],
         [123, 113, 160],
         ...,
         [ 74,  73, 115],
         [ 69,  68, 110],
         [ 66,  65, 107]],
 
        ...,
 
        [[ 39,  40,  74],
         [ 44,  45,  79],
         [ 50,  51,  85],
         ...,
         [ 23,  18,  39],
         [ 26,  19,  40],
         [ 28,  21,  42]],
 
        [[ 36,  38,  69],
         [ 40,  42,  73],
         [ 45,  47,  78],
         ...,
         [ 27,  20,  41],
         [ 28,  19,  40],
         [ 27,  18,  38]],
 
        [[ 36,  38,  69],
         [ 38,  40,  71],
         [ 42,  44,  75],
         ...,
         [ 28,  21,  42],
  

In [57]:
Y

[1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0]

In [58]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=1)

In [61]:
# Printing the shape of the testing data
x_train.shape

AttributeError: 'list' object has no attribute 'shape'

In [ ]:
from keras.applications.vgg16 import VGG16


In [ ]:
vgg=VGG16()

In [ ]:
vgg.summary()

In [ ]:
from keras.applications.vgg16 import VGG16
from keras import Sequential

# Load the pre-trained VGG16 model
vgg = VGG16()

# Create a new Sequential model
model = Sequential()

# Add layers from VGG16 to the new model, ignoring the last layer
for layer in vgg.layers[:-1]:  # Ignore the last layer
    model.add(layer)

# Display the summary of the new model
model.summary()
#see all same but last one has ignore

In [ ]:
#we have train the parameter
#now freeze all the layers
#ab hum sare ke sare layers ko freeze karage
#so train karne par weight update ho
#now we have freeze all layers( because weight and bais not update)
for layer in model.layers:
    layer.trainable=False


In [ ]:
#ye karne ke baat sab non-trainable band jayegey
#sab karne par aisa dekhaya dega
#ab saare trainable =0 hai, jitne bhi parameter hai vo non-trianable hai
#as a freeze ho gay ab update nahi kar sakte as a training time
model.summary()

In [ ]:
#abb hamara wal work karna hai ,hamara wala last layer main add hoga
from keras.layers import Dense

In [ ]:
model.add(Dense(units=1,activation='sigmoid'))

In [ ]:
model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])


In [ ]:
trained_model= model.fit(x_train,y_train,epochs=5,validation_data=(x_test,y_test))